### ISSUE TITLE
Is it Loklak JS API?

### ISSUE THREAD

**Issue by sevazhidkov** [sudheesh001/loklak-node#1]
Hi! 
If you want to create node.js wrapper for Loklak, please have a look for https://github.com/sevazhidkov/javascript-loklak-api

**Comment by sudheesh001** [comment]
Ah great ! Yup it was the Loklak JS API, Great, I was implementing it in another way. Looks like I'll continue with your implementation then. Thanks @sevazhidkov Once we have this test driven, lets fork it into loklak

**Comment by sevazhidkov** [comment]
Ok, I can add tests for current implemented methods

**Comment by sevazhidkov** [comment]
Which testing framework I can use?

**Comment by sudheesh001** [comment]
@sevazhidkov I've made a few changes and ensured that the code is perfectly linted, We probably need to work on this and enhance them to make it easier to use. Can it be made as simple as the python API where just `instance.function()` gives the response which can be loaded into a variable, That'd mean the major problem is with `async`. What do you think ?

**Comment by sudheesh001** [comment]
@sevazhidkov I've given you complete push access to this repository :+1: Thanks for the great work, lets enhance this library

**Comment by sevazhidkov** [comment]
Node.js modules often using in reactive frameworks (like Meteor). The paradigm of this frameworks is that we shouldn't wait some data from external services (like DB or API), because it brokes all reactive architecture.
For example, calling DB and showing information in view in Meteor looks like:

```
// Controller
Users.find(function (data) { Session.data = data })
// View
= Session.data
```

**Comment by sudheesh001** [comment]
Yes, You do have a point since the whole thing is event driven.
