### ISSUE TITLE
Integrate with Travis CI

### ISSUE THREAD

**Issue by sudheesh001** [sudheesh001/loklak-node#2]
The script to run the tests can either be `make test` or `npm test`.
Would you like to take this @sevazhidkov  ?

**Comment by sevazhidkov** [comment]
Yes, I will do it

**Comment by sudheesh001** [comment]
@sevazhidkov Great

**Comment by sudheesh001** [comment]
Once this is done, lets fork this into `loklak`

**Comment by sevazhidkov** [comment]
Travis automatically runs npm test command that runs make test
